name: Conexao_ArqPEAD_v2
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout2
        uses: actions/checkout@v2
    
      - name: CONEXAO SSH
        id: funny-deploy
        uses: BoatNg/funny-deploy@master
        env:
          REMOTE_HOST: "${{ secrets.ssh_host }}"
          REMOTE_USER: "${{ secrets.ssh_user }}"
          REMOTE_PASSWORD: "${{ secrets.ssh_pass }}"
          REMOTE_PATH: "/var/www/html/lixo"
        with:
          script: |
            echo RamonMaia 
            ls -a
            cd /var/www/html/lixo
            mkdir desenvolvimento
            ls
            pwd 
         


        
        
