name: Conexao_ArqPEAD
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Conexao com SSH Server 
        run: echo Conexao teste
      - name: Credenciais 
        run: whoami
        
             
        
        
