name: Conexao_ArqPEAD
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: deploy
        id: funny-deploy
        uses: BoatNg/funny-deploy@master
        env:
          REMOTE_HOST: "${{ secrets.ssh_host }}"
          REMOTE_USER: "${{ secrets.ssh_user }}"
          REMOTE_PASSWORD: "${{ secrets.ssh_pass }}"
          REMOTE_PATH: "/var/www/html/lixo"
          SOURCE: ""
        with:
          script: |
            ls -a
            cd /var/www/html/lixo
            mkdir desenvolvimento
            ls
            pwd 
         


        
        
